"""Research Agent package."""

from research_agent.contracts import (
    AuxiliaryTargetName,
    BaselineReproductionControl,
    BaselineStatus,
    BenchmarkContract,
    EvaluationProtocolStatus,
    EvidenceItem,
    EvidenceKind,
    EvidenceRequest,
    EvidenceRequestCategory,
    EvidenceStrength,
    ExperimentHistoryItem,
    ExperimentOutcome,
    ExperimentProposal,
    Hypothesis,
    InterpretationNextStep,
    OfficialFMConfig,
    ProposalPurpose,
    ResearchAgentFailure,
    ResearchContext,
    ResearchDecision,
    ResearchDecisionKind,
    ResearchEvaluationResult,
    ResearchFailureKind,
    ResearchInterpretation,
    ResearchLesson,
    ResearchMemoryQueryResult,
    ResearchMetricValue,
    ResearchRequest,
    ResearchResponse,
    ResearchTaskType,
    TargetAggregateTrainingStrategy,
    TargetDerivedFeatureControl,
)
from research_agent.graph import build_research_graph, run_research_graph
from research_agent.model import DeepSeekModelConfig, DeepSeekResearchModelClient
from research_agent.runtime import (
    Phase2Settings,
    build_phase2_capabilities,
    build_phase2_model_client,
)

__all__ = [
    "AuxiliaryTargetName",
    "BaselineReproductionControl",
    "BaselineStatus",
    "BenchmarkContract",
    "DeepSeekModelConfig",
    "DeepSeekResearchModelClient",
    "EvaluationProtocolStatus",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceRequest",
    "EvidenceRequestCategory",
    "EvidenceStrength",
    "ExperimentHistoryItem",
    "ExperimentOutcome",
    "ExperimentProposal",
    "Hypothesis",
    "InterpretationNextStep",
    "OfficialFMConfig",
    "Phase2Settings",
    "ProposalPurpose",
    "ResearchAgentFailure",
    "ResearchContext",
    "ResearchDecision",
    "ResearchDecisionKind",
    "ResearchEvaluationResult",
    "ResearchFailureKind",
    "ResearchInterpretation",
    "ResearchLesson",
    "ResearchMemoryQueryResult",
    "ResearchMetricValue",
    "ResearchRequest",
    "ResearchResponse",
    "ResearchTaskType",
    "TargetAggregateTrainingStrategy",
    "TargetDerivedFeatureControl",
    "build_phase2_capabilities",
    "build_phase2_model_client",
    "build_research_graph",
    "run_research_graph",
]
